stages: 
  - test
  - build
  - deploy

cache:
  paths: 
    - /node_modules/

before_script:
  - rm -rf build
  - CI=false yarn install

test project: 
  stage: test
  image: node:14
  script:
    - yarn install
    - yarn test -- --coverage --updateSnapshot

build project:
  stage: build
  image: node:14
  script:
    - yarn install
    - yarn build


pages:
  stage: deploy
  image: node:14
  script:
    - CI=false yarn run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
